"""  migration

Revision ID: 132978b25a27
Revises: 
Create Date: 2025-01-27 15:35:54.128303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '132978b25a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entree',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('idEntree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idEntree')
    )
    op.create_index('ix_entree_id', 'entree', ['idEntree'], unique=False)
    op.create_table('sortie',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('idSortie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('raison', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('idSortie')
    )
    op.create_index('ix_sortie_id', 'sortie', ['idSortie'], unique=False)
    op.create_table('type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('idType', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('idType')
    )
    op.create_index('ix_type_id', 'type', ['idType'], unique=False)
    op.create_table('detailentree',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('idDetailEntree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entree_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entree_id'], ['entree.idEntree'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.idType'], ),
    sa.PrimaryKeyConstraint('idDetailEntree')
    )
    op.create_index('ix_detail_entree_id', 'detailentree', ['idDetailEntree'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detail_entree_id', table_name='detailentree')
    op.drop_table('detailentree')
    op.drop_index('ix_type_id', table_name='type')
    op.drop_table('type')
    op.drop_index('ix_sortie_id', table_name='sortie')
    op.drop_table('sortie')
    op.drop_index('ix_entree_id', table_name='entree')
    op.drop_table('entree')
    # ### end Alembic commands ###
