"""final

Revision ID: 31144be24ef7
Revises: fc5efedfa4b8
Create Date: 2025-09-28 14:52:46.318180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31144be24ef7'
down_revision = 'fc5efedfa4b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entree_id', table_name='entree')
    op.drop_table('entree')
    op.drop_index('ix_montant_id', table_name='montant')
    op.drop_table('montant')
    op.drop_index('ix_detail_entree_id', table_name='detailentree')
    op.drop_table('detailentree')
    op.drop_index('ix_sortie_id', table_name='sortie')
    op.drop_table('sortie')
    op.drop_index('ix_type_id', table_name='type')
    op.drop_table('type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idType', sa.INTEGER(), server_default=sa.text('nextval(\'"type_idType_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idType', name='type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_type_id', 'type', ['idType'], unique=False)
    op.create_table('sortie',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idSortie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raison', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idSortie', name='sortie_pkey')
    )
    op.create_index('ix_sortie_id', 'sortie', ['idSortie'], unique=False)
    op.create_table('detailentree',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idDetailEntree', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entree_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entree_id'], ['entree.idEntree'], name='detailentree_entree_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['type.idType'], name='detailentree_type_id_fkey'),
    sa.PrimaryKeyConstraint('idDetailEntree', name='detailentree_pkey')
    )
    op.create_index('ix_detail_entree_id', 'detailentree', ['idDetailEntree'], unique=False)
    op.create_table('montant',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idMontant', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idMontant', name='montant_pkey')
    )
    op.create_index('ix_montant_id', 'montant', ['idMontant'], unique=False)
    op.create_table('entree',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idEntree', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idEntree', name='entree_pkey')
    )
    op.create_index('ix_entree_id', 'entree', ['idEntree'], unique=False)
    # ### end Alembic commands ###
